**Importando Bíbliotecas**

In [13]:
import pandas as pd
import numpy as np
pd.set_option("display.float_format", "{:,.2f}".format)

**Carregando Dados**

In [14]:
df = pd.read_csv('../data/TV Shows - Netflix.csv')

**Análise Inicial**

In [15]:
df.shape

(50, 5)

In [16]:
df.head(10)

                       Titles  Year Rating  IMDB_Rating  Netflix
0                Breaking Bad  2008    18+         9.50        1
1             Game of Thrones  2011    18+         9.30        0
2              Rick and Morty  2013    18+         9.20        0
3                        Dark  2017    16+         8.80        1
4             Stranger Things  2016    16+         8.80        1
5  Avatar: The Last Airbender  2005     7+         9.20        1
6                    Sherlock  2010    16+         9.10        1
7                   Chernobyl  2019    18+         9.40        0
8                     Friends  1994    16+         8.90        0
9                  The Office  2005    16+         8.90        1

In [17]:
df.tail(10)

                               Titles  Year Rating  IMDB_Rating  Netflix
40                             Fringe  2008    16+         8.40        0
41                      Modern Family  2009    16+         8.40        0
42                The Big Bang Theory  2007    16+         8.10        0
43                            Firefly  2002    16+         9.00        0
44                            Mad Men  2007    16+         8.60        0
45   Fullmetal Alchemist: Brotherhood  2009    18+         9.10        0
46                              Ozark  2017    18+         8.40        1
47                        The Witcher  2019    18+         8.20        1
48                            Lucifer  2016    16+         8.20        1
49  It's Always Sunny in Philadelphia  2005    18+         8.80        0

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Titles       50 non-null     str
 1   Year         50 non-null     int64
 2   Rating       50 non-null     str
 3   IMDB_Rating  50 non-null     float64
 4   Netflix      50 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 2.8 KB

In [19]:
df.describe()

          Year  IMDB_Rating  Netflix
count    50.00        50.00    50.00
mean  2,009.90         8.72     0.38
std       6.75         0.36     0.49
min   1,989.00         8.00     0.00
25%   2,005.25         8.50     0.00
50%   2,011.00         8.70     0.00
75%   2,015.00         8.90     1.00
max   2,019.00         9.50     1.00